"""
Sentinel table schema loader.

Reads config/sentinel_tables.json (generated by scripts/discover_sentinel_schemas.py)
and auto-classifies tables by IOC type based on column names.

Returns table definitions in the format expected by generate_queries.py:
    (table_name, [ioc_fields], project_columns_str, description)
"""
from __future__ import annotations

import json
from pathlib import Path

_SCHEMA_PATH = Path(__file__).resolve().parent / "sentinel_tables.json"

# ---------------------------------------------------------------------------
# Column → IOC-type classification rules
# ---------------------------------------------------------------------------
# Each rule: exact column name → (ioc_type, search_operator)
# "in" = exact match (IP lists), "has" = substring match (domains/URLs)

_IP_FIELDS = {
    "RemoteIP", "LocalIP", "SourceIPAddress", "DestinationIPAddress",
    "IPAddress", "IpAddress", "HostIP", "CallerIpAddress", "ClientIP",
    "SalIpAddress", "SourceIP",
}

_DOMAIN_FIELDS = {
    "RemoteUrl",        # DeviceNetworkEvents — has domain in URL
    "QueryTarget",      # IdentityQueryEvents
    "UrlDomain",        # EmailUrlInfo
    "DstDomain",        # ASIM normalized
    "SrcDomain",        # ASIM normalized
    "DstFQDN",          # ASIM normalized
    # NOTE: "DomainName" excluded — it's AD domain in SecurityEvent/AAD tables,
    # not network domain.  OktaV2 is the exception but not worth the false positives.
}

_URL_FIELDS = {
    "RemoteUrl",        # DeviceNetworkEvents
    "Url",              # EmailUrlInfo
    "UrlFull",          # ASIM
    "RequestURL",       # CommonSecurityLog
}

_HASH_FIELDS = {
    # sha256
    "SHA256": "sha256", "InitiatingProcessSHA256": "sha256", "Sha256": "sha256",
    "FileSHA256": "sha256", "SHA_SHA256_s": "sha256",
    # sha1
    "SHA1": "sha1", "InitiatingProcessSHA1": "sha1", "Sha1": "sha1",
    "FileSHA1": "sha1",
    # md5
    "MD5": "md5", "InitiatingProcessMD5": "md5", "Md5": "md5",
    "FileMD5": "md5",
    # generic
    "FileHash": "sha256",  # CommonSecurityLog — assume sha256 for query
}

_EMAIL_FIELDS = {
    "SenderFromAddress", "RecipientEmailAddress", "SenderMailFromAddress",
    "UserPrincipalName",
}

# Tables to skip — infrastructure/ops noise, not useful for IOC hunting
_SKIP_TABLES = {
    "Usage", "Operation", "Heartbeat", "AzureMetrics", "AzureDiagnostics",
    "LAQueryLogs", "SentinelHealth", "SentinelAudit", "Watchlist",
    "InsightsMetrics", "Perf", "ProtectionStatus", "Update", "UpdateSummary",
    "ConfigurationChange", "ConfigurationData", "HealthStateChangeEvent",
    "SecureScoreControls", "SecureScores", "SecurityBaseline",
    "SecurityBaselineSummary", "SecurityNestedRecommendation",
    "SecurityRecommendation", "SecurityRegulatoryCompliance",
    "VMBoundPort", "VMComputer", "VMConnection", "VMProcess",
    "WVDAgentHealthStatus", "WVDCheckpoints", "WVDConnectionGraphicsDataPreview",
    "WVDConnectionNetworkData", "WVDConnections", "WVDErrors", "WVDFeeds",
    "WVDManagement", "UCClient", "UCClientUpdateStatus", "UCDOAggregatedStatus",
    "UCDOStatus", "UCDeviceAlert", "UCServiceUpdateStatus", "UCUpdateAlert",
    "AppMetrics", "AppPerformanceCounters", "AppBrowserTimings",
    "AppDependencies", "AppEvents", "AppExceptions", "AppPageViews",
    "AppSystemEvents", "AppRequests", "AppTraces",
    # App Insights telemetry — not security-relevant
    "ContainerRegistryLoginEvents", "ContainerRegistryRepositoryEvents",
    "ApiManagementGatewayLogs", "FunctionAppLogs", "AppServiceAppLogs",
    "AppServiceAuditLogs", "AppServiceFileAuditLogs", "AppServiceHTTPLogs",
    "AppServiceIPSecAuditLogs",
    # Azure PaaS service logs — rarely useful for IOC hunting
    "StorageBlobLogs", "StorageFileLogs", "StorageQueueLogs", "StorageTableLogs",
    # Azure Storage diagnostics — high volume, low signal for IOC hunts
    "AddonAzureBackupJobs", "AddonAzureBackupPolicy",
    "AddonAzureBackupProtectedInstance", "AddonAzureBackupStorage",
    "CoreAzureBackup", "ASRReplicatedItems",
    "NetworkMonitoring", "NTAIpDetails", "NTANetAnalytics", "NTATopologyDetails",
    "WindowsFirewall",
}

# Context columns to include in project (priority order, pick first N available)
_CONTEXT_PRIORITY = [
    "TimeGenerated", "DeviceName", "Computer", "ComputerName",
    "AccountName", "Account", "UserPrincipalName", "UserName",
    "InitiatingProcessFileName", "FileName", "ProcessName",
    "InitiatingProcessCommandLine", "ProcessCommandLine", "CommandLine",
    "ActionType", "Activity", "OperationName",
    "FolderPath", "FilePath",
]

# ---------------------------------------------------------------------------
# Registry cache
# ---------------------------------------------------------------------------
_registry: dict | None = None


def _load_registry() -> dict:
    global _registry
    if _registry is not None:
        return _registry
    if not _SCHEMA_PATH.exists():
        _registry = {}
        return _registry
    with open(_SCHEMA_PATH) as f:
        _registry = json.load(f)
    return _registry


def _build_project(table_cols: dict, ioc_fields: list[str], max_extra: int = 5) -> str:
    """Build a project column string: IOC fields + context columns."""
    cols = []
    # Always start with TimeGenerated if present
    if "TimeGenerated" in table_cols:
        cols.append("TimeGenerated")
    # Add IOC fields
    for f in ioc_fields:
        if f not in cols:
            cols.append(f)
    # Add context columns
    for ctx in _CONTEXT_PRIORITY:
        if ctx in table_cols and ctx not in cols:
            cols.append(ctx)
            if len(cols) >= len(ioc_fields) + max_extra + 1:
                break
    return ", ".join(cols)


def _table_description(table_name: str) -> str:
    """Generate a short description based on table name."""
    # Known descriptions for common tables
    _KNOWN = {
        "DeviceNetworkEvents": "Network connections",
        "DeviceFileEvents": "File system events",
        "DeviceProcessEvents": "Process creation events",
        "DeviceImageLoadEvents": "Module / DLL load events",
        "DeviceLogonEvents": "Device logon events",
        "DeviceRegistryEvents": "Registry events",
        "DeviceEvents": "Misc device events",
        "DeviceInfo": "Device inventory",
        "DeviceNetworkInfo": "Network adapter / IP assignment",
        "DeviceFileCertificateInfo": "File certificate info",
        "IdentityLogonEvents": "Authentication events",
        "IdentityQueryEvents": "Directory service queries",
        "IdentityDirectoryEvents": "Directory changes",
        "IdentityInfo": "Identity inventory",
        "SecurityEvent": "Windows security events",
        "SecurityAlert": "Security alerts",
        "SecurityIncident": "Security incidents",
        "AlertEvidence": "Alert evidence",
        "AlertInfo": "Alert info",
        "Anomalies": "UEBA anomalies",
        "BehaviorAnalytics": "UEBA behavior analytics",
        "SigninLogs": "Entra ID interactive sign-ins",
        "AADNonInteractiveUserSignInLogs": "Entra ID non-interactive sign-ins",
        "AADManagedIdentitySignInLogs": "Managed identity sign-ins",
        "AADServicePrincipalSignInLogs": "Service principal sign-ins",
        "AADUserRiskEvents": "User risk events",
        "AADRiskyUsers": "Risky users",
        "AuditLogs": "Entra ID audit logs",
        "EmailEvents": "Email delivery events",
        "EmailUrlInfo": "URLs in emails",
        "EmailAttachmentInfo": "Email attachments",
        "EmailPostDeliveryEvents": "Post-delivery email actions",
        "UrlClickEvents": "Safe Links click events",
        "CloudAppEvents": "Cloud app activity",
        "OfficeActivity": "Office 365 activity",
        "CommonSecurityLog": "CEF syslog (firewalls, proxies)",
        "Syslog": "Linux/Unix syslog",
        "ThreatIntelIndicators": "Threat intelligence indicators",
        "McasShadowItReporting": "MCAS shadow IT",
        "MicrosoftGraphActivityLogs": "Graph API activity",
        "MicrosoftPurviewInformationProtection": "Purview DLP",
        "PowerBIActivity": "Power BI activity",
        "Dynamics365Activity": "Dynamics 365 activity",
        "IntuneAuditLogs": "Intune audit",
        "IntuneDevices": "Intune device inventory",
        "AzureActivity": "Azure control plane activity",
        "StorageBlobLogs": "Azure Blob storage logs",
        "StorageFileLogs": "Azure File storage logs",
        "CrowdStrikeAlerts": "CrowdStrike alerts",
        "CrowdStrikeDetections": "CrowdStrike detections",
        "Event": "Windows events (legacy)",
        "GCPAuditLogs": "Google Cloud audit logs",
        "GoogleCloudSCC": "Google Cloud Security Command Center",
        "NetworkAccessTraffic": "Global Secure Access traffic",
    }
    if table_name in _KNOWN:
        return _KNOWN[table_name]
    # Custom/CL tables — use the table name itself
    if table_name.endswith("_CL"):
        return f"Custom: {table_name.replace('_CL', '')}"
    return table_name


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def get_ip_tables(allowed: list[str] | None = None) -> list[tuple]:
    """Tables with IPv4 IOC fields."""
    registry = _load_registry()
    results = []
    for table, info in sorted(registry.items()):
        if table in _SKIP_TABLES:
            continue
        if allowed and table not in allowed:
            continue
        cols = info["columns"]
        ip_fields = [c for c in cols if c in _IP_FIELDS]
        if not ip_fields:
            continue
        project = _build_project(cols, ip_fields)
        results.append((table, ip_fields, project, _table_description(table)))
    return results


def get_domain_tables(allowed: list[str] | None = None) -> list[tuple]:
    """Tables with domain IOC fields."""
    registry = _load_registry()
    results = []
    for table, info in sorted(registry.items()):
        if table in _SKIP_TABLES:
            continue
        if allowed and table not in allowed:
            continue
        cols = info["columns"]
        dom_fields = [c for c in cols if c in _DOMAIN_FIELDS]
        if not dom_fields:
            continue
        project = _build_project(cols, dom_fields)
        results.append((table, dom_fields, project, _table_description(table)))
    return results


def get_url_tables(allowed: list[str] | None = None) -> list[tuple]:
    """Tables with URL IOC fields."""
    registry = _load_registry()
    results = []
    for table, info in sorted(registry.items()):
        if table in _SKIP_TABLES:
            continue
        if allowed and table not in allowed:
            continue
        cols = info["columns"]
        url_fields = [c for c in cols if c in _URL_FIELDS]
        if not url_fields:
            continue
        project = _build_project(cols, url_fields)
        results.append((table, url_fields, project, _table_description(table)))
    return results


def get_hash_tables(hash_type: str, allowed: list[str] | None = None) -> list[tuple]:
    """Tables with hash IOC fields for a given hash type (sha256/md5/sha1)."""
    registry = _load_registry()
    results = []
    for table, info in sorted(registry.items()):
        if table in _SKIP_TABLES:
            continue
        if allowed and table not in allowed:
            continue
        cols = info["columns"]
        hash_fields = [c for c in cols if c in _HASH_FIELDS and _HASH_FIELDS[c] == hash_type]
        if not hash_fields:
            continue
        project = _build_project(cols, hash_fields)
        results.append((table, hash_fields, project, _table_description(table)))
    return results


def get_email_tables(allowed: list[str] | None = None) -> list[tuple]:
    """Tables with email IOC fields."""
    registry = _load_registry()
    results = []
    for table, info in sorted(registry.items()):
        if table in _SKIP_TABLES:
            continue
        if allowed and table not in allowed:
            continue
        cols = info["columns"]
        email_fields = [c for c in cols if c in _EMAIL_FIELDS]
        if not email_fields:
            continue
        project = _build_project(cols, email_fields)
        results.append((table, email_fields, project, _table_description(table)))
    return results


def get_all_table_names() -> list[str]:
    """All table names in the registry."""
    return sorted(_load_registry().keys())


def get_table_columns(table_name: str) -> dict[str, str]:
    """Column name → type mapping for a specific table."""
    registry = _load_registry()
    entry = registry.get(table_name, {})
    return entry.get("columns", {})


def get_table_workspaces(table_name: str) -> list[str]:
    """Workspace codes where this table exists."""
    registry = _load_registry()
    entry = registry.get(table_name, {})
    return entry.get("workspaces", [])


def has_registry() -> bool:
    """Check if sentinel_tables.json exists and has data."""
    registry = _load_registry()
    return len(registry) > 0
