"""
Sentinel table schema loader.

Reads config/sentinel_tables.json (generated by scripts/discover_sentinel_schemas.py)
and auto-classifies tables by IOC type based on column names.

Returns table definitions in the format expected by generate_queries.py:
    (table_name, [ioc_fields], project_columns_str, description)
"""
from __future__ import annotations

import json
import re
from pathlib import Path

_SCHEMA_PATH = Path(__file__).resolve().parent / "sentinel_tables.json"
_WORKSPACE_PATH = Path(__file__).resolve().parent / "workspace_tables.json"

# ---------------------------------------------------------------------------
# Column → IOC-type classification rules
# ---------------------------------------------------------------------------
# Each rule: exact column name → (ioc_type, search_operator)
# "in" = exact match (IP lists), "has" = substring match (domains/URLs)

_IP_FIELDS = {
    "RemoteIP", "LocalIP", "SourceIPAddress", "DestinationIPAddress",
    "IPAddress", "IpAddress", "HostIP", "CallerIpAddress", "ClientIP",
    "SalIpAddress", "SourceIP",
}

_DOMAIN_FIELDS = {
    "RemoteUrl",        # DeviceNetworkEvents — has domain in URL
    "QueryTarget",      # IdentityQueryEvents
    "UrlDomain",        # EmailUrlInfo
    "DstDomain",        # ASIM normalized
    "SrcDomain",        # ASIM normalized
    "DstFQDN",          # ASIM normalized
    # NOTE: "DomainName" excluded — it's AD domain in SecurityEvent/AAD tables,
    # not network domain.  OktaV2 is the exception but not worth the false positives.
}

_URL_FIELDS = {
    "RemoteUrl",        # DeviceNetworkEvents
    "Url",              # EmailUrlInfo
    "UrlFull",          # ASIM
    "RequestURL",       # CommonSecurityLog
}

_HASH_FIELDS = {
    # sha256
    "SHA256": "sha256", "InitiatingProcessSHA256": "sha256", "Sha256": "sha256",
    "FileSHA256": "sha256", "SHA_SHA256_s": "sha256",
    # sha1
    "SHA1": "sha1", "InitiatingProcessSHA1": "sha1", "Sha1": "sha1",
    "FileSHA1": "sha1",
    # md5
    "MD5": "md5", "InitiatingProcessMD5": "md5", "Md5": "md5",
    "FileMD5": "md5",
    # generic
    "FileHash": "sha256",  # CommonSecurityLog — assume sha256 for query
}

_EMAIL_FIELDS = {
    "SenderFromAddress", "RecipientEmailAddress", "SenderMailFromAddress",
    "UserPrincipalName",
}

# Tables to skip — infrastructure/ops noise, not useful for IOC hunting
_SKIP_TABLES = {
    "Usage", "Operation", "Heartbeat", "AzureMetrics", "AzureDiagnostics",
    "LAQueryLogs", "SentinelHealth", "SentinelAudit", "Watchlist",
    "InsightsMetrics", "Perf", "ProtectionStatus", "Update", "UpdateSummary",
    "ConfigurationChange", "ConfigurationData", "HealthStateChangeEvent",
    "SecureScoreControls", "SecureScores", "SecurityBaseline",
    "SecurityBaselineSummary", "SecurityNestedRecommendation",
    "SecurityRecommendation", "SecurityRegulatoryCompliance",
    "VMBoundPort", "VMComputer", "VMConnection", "VMProcess",
    "WVDAgentHealthStatus", "WVDCheckpoints", "WVDConnectionGraphicsDataPreview",
    "WVDConnectionNetworkData", "WVDConnections", "WVDErrors", "WVDFeeds",
    "WVDManagement", "UCClient", "UCClientUpdateStatus", "UCDOAggregatedStatus",
    "UCDOStatus", "UCDeviceAlert", "UCServiceUpdateStatus", "UCUpdateAlert",
    "AppMetrics", "AppPerformanceCounters", "AppBrowserTimings",
    "AppDependencies", "AppEvents", "AppExceptions", "AppPageViews",
    "AppSystemEvents", "AppRequests", "AppTraces",
    # App Insights telemetry — not security-relevant
    "ContainerRegistryLoginEvents", "ContainerRegistryRepositoryEvents",
    "ApiManagementGatewayLogs", "FunctionAppLogs", "AppServiceAppLogs",
    "AppServiceAuditLogs", "AppServiceFileAuditLogs", "AppServiceHTTPLogs",
    "AppServiceIPSecAuditLogs",
    # Azure PaaS service logs — rarely useful for IOC hunting
    "StorageBlobLogs", "StorageFileLogs", "StorageQueueLogs", "StorageTableLogs",
    # Azure Storage diagnostics — high volume, low signal for IOC hunts
    "AddonAzureBackupJobs", "AddonAzureBackupPolicy",
    "AddonAzureBackupProtectedInstance", "AddonAzureBackupStorage",
    "CoreAzureBackup", "ASRReplicatedItems",
    "NetworkMonitoring", "NTAIpDetails", "NTANetAnalytics", "NTATopologyDetails",
    "WindowsFirewall",
}

# Context columns to include in project (priority order, pick first N available)
_CONTEXT_PRIORITY = [
    "TimeGenerated", "DeviceName", "Computer", "ComputerName",
    "AccountName", "Account", "UserPrincipalName", "UserName",
    "InitiatingProcessFileName", "FileName", "ProcessName",
    "InitiatingProcessCommandLine", "ProcessCommandLine", "CommandLine",
    "ActionType", "Activity", "OperationName",
    "FolderPath", "FilePath",
]

# ---------------------------------------------------------------------------
# Registry cache
# ---------------------------------------------------------------------------
_registry: dict | None = None
_workspace_registry: dict | None = None


def _load_registry() -> dict:
    global _registry
    if _registry is not None:
        return _registry
    if not _SCHEMA_PATH.exists():
        _registry = {}
        return _registry
    with open(_SCHEMA_PATH) as f:
        _registry = json.load(f)
    return _registry


def _load_workspace_tables() -> dict:
    """Load per-workspace table availability from workspace_tables.json."""
    global _workspace_registry
    if _workspace_registry is not None:
        return _workspace_registry
    if not _WORKSPACE_PATH.exists():
        _workspace_registry = {}
        return _workspace_registry
    with open(_WORKSPACE_PATH) as f:
        _workspace_registry = json.load(f)
    return _workspace_registry


def _build_project(table_cols: dict, ioc_fields: list[str], max_extra: int = 5) -> str:
    """Build a project column string: IOC fields + context columns."""
    cols = []
    # Always start with TimeGenerated if present
    if "TimeGenerated" in table_cols:
        cols.append("TimeGenerated")
    # Add IOC fields
    for f in ioc_fields:
        if f not in cols:
            cols.append(f)
    # Add context columns
    for ctx in _CONTEXT_PRIORITY:
        if ctx in table_cols and ctx not in cols:
            cols.append(ctx)
            if len(cols) >= len(ioc_fields) + max_extra + 1:
                break
    return ", ".join(cols)


def _table_description(table_name: str) -> str:
    """Generate a short description based on table name."""
    # Known descriptions for common tables
    _KNOWN = {
        "DeviceNetworkEvents": "Network connections",
        "DeviceFileEvents": "File system events",
        "DeviceProcessEvents": "Process creation events",
        "DeviceImageLoadEvents": "Module / DLL load events",
        "DeviceLogonEvents": "Device logon events",
        "DeviceRegistryEvents": "Registry events",
        "DeviceEvents": "Misc device events",
        "DeviceInfo": "Device inventory",
        "DeviceNetworkInfo": "Network adapter / IP assignment",
        "DeviceFileCertificateInfo": "File certificate info",
        "IdentityLogonEvents": "Authentication events",
        "IdentityQueryEvents": "Directory service queries",
        "IdentityDirectoryEvents": "Directory changes",
        "IdentityInfo": "Identity inventory",
        "SecurityEvent": "Windows security events",
        "SecurityAlert": "Security alerts",
        "SecurityIncident": "Security incidents",
        "AlertEvidence": "Alert evidence",
        "AlertInfo": "Alert info",
        "Anomalies": "UEBA anomalies",
        "BehaviorAnalytics": "UEBA behavior analytics",
        "SigninLogs": "Entra ID interactive sign-ins",
        "AADNonInteractiveUserSignInLogs": "Entra ID non-interactive sign-ins",
        "AADManagedIdentitySignInLogs": "Managed identity sign-ins",
        "AADServicePrincipalSignInLogs": "Service principal sign-ins",
        "AADUserRiskEvents": "User risk events",
        "AADRiskyUsers": "Risky users",
        "AuditLogs": "Entra ID audit logs",
        "EmailEvents": "Email delivery events",
        "EmailUrlInfo": "URLs in emails",
        "EmailAttachmentInfo": "Email attachments",
        "EmailPostDeliveryEvents": "Post-delivery email actions",
        "UrlClickEvents": "Safe Links click events",
        "CloudAppEvents": "Cloud app activity",
        "OfficeActivity": "Office 365 activity",
        "CommonSecurityLog": "CEF syslog (firewalls, proxies)",
        "Syslog": "Linux/Unix syslog",
        "ThreatIntelIndicators": "Threat intelligence indicators",
        "McasShadowItReporting": "MCAS shadow IT",
        "MicrosoftGraphActivityLogs": "Graph API activity",
        "MicrosoftPurviewInformationProtection": "Purview DLP",
        "PowerBIActivity": "Power BI activity",
        "Dynamics365Activity": "Dynamics 365 activity",
        "IntuneAuditLogs": "Intune audit",
        "IntuneDevices": "Intune device inventory",
        "AzureActivity": "Azure control plane activity",
        "StorageBlobLogs": "Azure Blob storage logs",
        "StorageFileLogs": "Azure File storage logs",
        "CrowdStrikeAlerts": "CrowdStrike alerts",
        "CrowdStrikeDetections": "CrowdStrike detections",
        "Event": "Windows events (legacy)",
        "GCPAuditLogs": "Google Cloud audit logs",
        "GoogleCloudSCC": "Google Cloud Security Command Center",
        "NetworkAccessTraffic": "Global Secure Access traffic",
    }
    if table_name in _KNOWN:
        return _KNOWN[table_name]
    # Custom/CL tables — use the table name itself
    if table_name.endswith("_CL"):
        return f"Custom: {table_name.replace('_CL', '')}"
    return table_name


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def get_ip_tables(allowed: list[str] | None = None) -> list[tuple]:
    """Tables with IPv4 IOC fields."""
    registry = _load_registry()
    results = []
    for table, info in sorted(registry.items()):
        if table in _SKIP_TABLES:
            continue
        if allowed and table not in allowed:
            continue
        cols = info["columns"]
        ip_fields = [c for c in cols if c in _IP_FIELDS]
        if not ip_fields:
            continue
        project = _build_project(cols, ip_fields)
        results.append((table, ip_fields, project, _table_description(table)))
    return results


def get_domain_tables(allowed: list[str] | None = None) -> list[tuple]:
    """Tables with domain IOC fields."""
    registry = _load_registry()
    results = []
    for table, info in sorted(registry.items()):
        if table in _SKIP_TABLES:
            continue
        if allowed and table not in allowed:
            continue
        cols = info["columns"]
        dom_fields = [c for c in cols if c in _DOMAIN_FIELDS]
        if not dom_fields:
            continue
        project = _build_project(cols, dom_fields)
        results.append((table, dom_fields, project, _table_description(table)))
    return results


def get_url_tables(allowed: list[str] | None = None) -> list[tuple]:
    """Tables with URL IOC fields."""
    registry = _load_registry()
    results = []
    for table, info in sorted(registry.items()):
        if table in _SKIP_TABLES:
            continue
        if allowed and table not in allowed:
            continue
        cols = info["columns"]
        url_fields = [c for c in cols if c in _URL_FIELDS]
        if not url_fields:
            continue
        project = _build_project(cols, url_fields)
        results.append((table, url_fields, project, _table_description(table)))
    return results


def get_hash_tables(hash_type: str, allowed: list[str] | None = None) -> list[tuple]:
    """Tables with hash IOC fields for a given hash type (sha256/md5/sha1)."""
    registry = _load_registry()
    results = []
    for table, info in sorted(registry.items()):
        if table in _SKIP_TABLES:
            continue
        if allowed and table not in allowed:
            continue
        cols = info["columns"]
        hash_fields = [c for c in cols if c in _HASH_FIELDS and _HASH_FIELDS[c] == hash_type]
        if not hash_fields:
            continue
        project = _build_project(cols, hash_fields)
        results.append((table, hash_fields, project, _table_description(table)))
    return results


def get_email_tables(allowed: list[str] | None = None) -> list[tuple]:
    """Tables with email IOC fields."""
    registry = _load_registry()
    results = []
    for table, info in sorted(registry.items()):
        if table in _SKIP_TABLES:
            continue
        if allowed and table not in allowed:
            continue
        cols = info["columns"]
        email_fields = [c for c in cols if c in _EMAIL_FIELDS]
        if not email_fields:
            continue
        project = _build_project(cols, email_fields)
        results.append((table, email_fields, project, _table_description(table)))
    return results


def get_all_table_names() -> list[str]:
    """All table names in the registry."""
    return sorted(_load_registry().keys())


def get_table_columns(table_name: str) -> dict[str, str]:
    """Column name → type mapping for a specific table."""
    registry = _load_registry()
    entry = registry.get(table_name, {})
    return entry.get("columns", {})


def get_table_workspaces(table_name: str) -> list[str]:
    """Workspace codes where this table exists."""
    registry = _load_registry()
    entry = registry.get(table_name, {})
    return entry.get("workspaces", [])


def has_registry() -> bool:
    """Check if sentinel_tables.json exists and has data."""
    registry = _load_registry()
    return len(registry) > 0


# ---------------------------------------------------------------------------
# Workspace-scoped table lookup
# ---------------------------------------------------------------------------

def get_workspace_tables(workspace: str) -> set[str]:
    """Return the set of table names available in a workspace.

    ``workspace`` can be a workspace code (e.g. ``"performanta"``) or a
    workspace GUID.  Returns an empty set if the workspace is unknown or
    the workspace index file is missing.
    """
    ws = _load_workspace_tables()
    if not ws:
        return set()
    # Try exact code match, then case-insensitive
    entry = ws.get(workspace) or ws.get(workspace.lower())
    if entry:
        return set(entry.get("tables", []))
    # Try GUID match (iterate values)
    for info in ws.values():
        if info.get("workspace_id") == workspace:
            return set(info.get("tables", []))
    return set()


def resolve_workspace_code(workspace_id: str) -> str:
    """Reverse-lookup workspace code from a GUID.  Returns ``""`` if unknown."""
    ws = _load_workspace_tables()
    for code, info in ws.items():
        if info.get("workspace_id") == workspace_id:
            return code
    return ""


# ---------------------------------------------------------------------------
# KQL table extraction
# ---------------------------------------------------------------------------

# Patterns to find table references in KQL.
# Pattern 1: bare table at start of line followed by pipe on same or next line
#   e.g.  "SigninLogs\n| where ..." or "SigninLogs | where ..."
# Pattern 2: let assignment  "let Foo = TableName\n| where ..."
# Pattern 3: join subquery   "join kind=inner ( TableName\n| ..."
_KQL_TABLE_PATTERNS = [
    re.compile(r'^\s*(\w+)\s*$\n\s*\|', re.MULTILINE),
    re.compile(r'^\s*(\w+)\s*\|', re.MULTILINE),
    re.compile(r'let\s+\w+\s*=\s*(\w+)\s*\n\s*\|', re.MULTILINE),
    re.compile(r'let\s+\w+\s*=\s*(\w+)\s*\|', re.MULTILINE),
    re.compile(r'\(\s*(\w+)\s*\n\s*\|', re.MULTILINE),
    # union Table1, Table2 (ad-hoc analyst queries)
    re.compile(r'union\s+(?:isfuzzy\s*=\s*\w+\s+)?(\w+)', re.MULTILINE),
    re.compile(r'union\s+(?:isfuzzy\s*=\s*\w+\s+)?\w+\s*,\s*(\w+)', re.MULTILINE),
]

# KQL keywords and operators that should never be treated as table names
_KQL_KEYWORDS = {
    "let", "union", "join", "extend", "project", "where", "summarize",
    "sort", "order", "take", "limit", "top", "count", "distinct",
    "render", "evaluate", "parse", "mv", "search", "find", "print",
    "datatable", "range", "materialize", "toscalar", "dynamic",
    "true", "false", "and", "or", "not", "in", "has", "contains",
    "between", "ago", "now", "datetime", "timespan", "isfuzzy",
    "kind", "inner", "leftouter", "rightouter", "fullouter",
    "by", "on", "asc", "desc", "with", "typeof", "pack_array",
    "array_concat", "isnotempty", "isempty", "iff", "iif",
    "tostring", "toint", "tolong", "todouble", "todecimal",
    "make_set", "make_list", "make_set_if", "dcount", "min", "max",
    "avg", "sum", "count_", "any", "arg_max", "arg_min",
    "strcat", "substring", "split", "trim", "replace",
    "datetime_diff", "format_datetime", "bin", "floor", "ceiling",
}


def extract_tables_from_kql(query: str) -> set[str]:
    """Extract referenced Sentinel table names from a KQL query string.

    Uses regex patterns to find candidate table names, then filters them
    against the schema registry to eliminate ``let`` variable names and
    KQL keywords.  If the registry is absent, returns candidates that
    look like known Sentinel table patterns (capitalised, no underscores
    except ``_CL`` suffix).
    """
    candidates: set[str] = set()
    for pattern in _KQL_TABLE_PATTERNS:
        for m in pattern.finditer(query):
            name = m.group(1)
            if name and name.lower() not in _KQL_KEYWORDS:
                candidates.add(name)

    if not candidates:
        return set()

    # Filter against known table names in the registry
    registry = _load_registry()
    if registry:
        known = set(registry.keys())
        return candidates & known

    # No registry — best-effort heuristic: keep names that start with
    # uppercase and are not common KQL variable names
    return {c for c in candidates if c[0].isupper() and len(c) > 2}


# ---------------------------------------------------------------------------
# Table validation
# ---------------------------------------------------------------------------

def validate_tables(
    tables: list[str],
    workspace: str = "",
) -> dict:
    """Validate a list of table names against the schema registry.

    Returns a dict with:
      - ``valid``: always ``True`` (warnings are advisory, never blocking)
      - ``warnings``: list of human-readable warning strings
      - ``missing_tables``: tables not found in the target workspace
      - ``unknown_tables``: tables not found in the universal registry
    """
    result = {
        "valid": True,
        "warnings": [],
        "missing_tables": [],
        "unknown_tables": [],
    }

    if not tables:
        return result

    registry = _load_registry()
    if not registry:
        result["warnings"].append(
            "Schema registry not available — run scripts/discover_sentinel_schemas.py to enable validation."
        )
        return result

    known = set(registry.keys())

    for table in tables:
        if table not in known:
            result["unknown_tables"].append(table)
            result["warnings"].append(
                f"Table '{table}' not found in schema registry."
            )

    if workspace:
        ws_tables = get_workspace_tables(workspace)
        if ws_tables:
            for table in tables:
                if table in known and table not in ws_tables:
                    result["missing_tables"].append(table)
                    result["warnings"].append(
                        f"Table '{table}' exists in registry but not in workspace '{workspace}' — query section will return 0 rows."
                    )

    return result


# ---------------------------------------------------------------------------
# Schema summary for prompt injection
# ---------------------------------------------------------------------------

_TYPE_SIMPLIFY = {
    "System.String": "String",
    "System.DateTime": "DateTime",
    "System.Int32": "Int",
    "System.Int64": "Long",
    "System.Double": "Double",
    "System.Boolean": "Bool",
    "System.Guid": "Guid",
    "System.Object": "Dynamic",
    "System.SByte": "SByte",
    "System.TimeSpan": "TimeSpan",
    "string": "String",
    "datetime": "DateTime",
    "int": "Int",
    "long": "Long",
    "double": "Double",
    "bool": "Bool",
    "guid": "Guid",
    "dynamic": "Dynamic",
    "timespan": "TimeSpan",
    "real": "Double",
}

# All IOC-classified fields (union of sets/keys)
_ALL_IOC_FIELDS = (
    _IP_FIELDS | _DOMAIN_FIELDS | _URL_FIELDS | _EMAIL_FIELDS | set(_HASH_FIELDS.keys())
)


def get_table_schema_summary(table: str, max_columns: int = 25) -> str:
    """Return a compact text summary of a table's columns for prompt injection.

    Columns are ordered by investigation relevance: context priority columns
    first, then IOC fields, then remaining columns alphabetically.
    Types are simplified (e.g. ``System.String`` → ``String``).

    Returns an empty string if the table is not in the registry.
    """
    registry = _load_registry()
    entry = registry.get(table)
    if not entry:
        return ""

    columns = entry.get("columns", {})
    if not columns:
        return ""

    # Build ordered column list: priority → IOC → alphabetical
    ordered: list[str] = []
    seen: set[str] = set()

    for col in _CONTEXT_PRIORITY:
        if col in columns and col not in seen:
            ordered.append(col)
            seen.add(col)

    for col in sorted(_ALL_IOC_FIELDS):
        if col in columns and col not in seen:
            ordered.append(col)
            seen.add(col)

    for col in sorted(columns.keys()):
        if col not in seen:
            ordered.append(col)
            seen.add(col)

    total = len(ordered)
    display = ordered[:max_columns]

    def _simplify(t: str) -> str:
        return _TYPE_SIMPLIFY.get(t, t.replace("System.", ""))

    lines = []
    desc = _table_description(table)
    lines.append(f"{table} — {desc} ({total} columns)")
    for col in display:
        lines.append(f"  {col}: {_simplify(columns[col])}")
    if total > max_columns:
        lines.append(f"  ... +{total - max_columns} more columns")

    return "\n".join(lines)
