"""
tool: save_report
-----------------
Lightweight report persistence for client-side (Claude Desktop) generated reports.

When the analyst's local Claude session generates a report using an MCP prompt,
this tool handles the write-back: dealiasing, defanging, HTML conversion,
auto-close logic, audit trail, and manifest generation.

No LLM call — all the "thinking" was done by the local session.

Usage (MCP only — called via save_report tool):
    save_report(case_id, report_type, report_text, disposition=None)
"""
from __future__ import annotations

import json
import sys
import traceback as tb
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from config.settings import CASES_DIR
from tools.common import (
    defang_report, get_alias_map, load_json, log_error, save_json,
    utcnow, write_report,
)


# ---------------------------------------------------------------------------
# Report type configuration
# ---------------------------------------------------------------------------

_REPORT_TYPES = {
    "mdr_report": {
        "path": "reports/mdr_report.html",
        "title_prefix": "MDR Incident Report",
        "auto_close": True,
        "disposition": None,        # preserves existing
        "defang": True,
    },
    "pup_report": {
        "path": "reports/pup_report.html",
        "title_prefix": "PUP/PUA Report",
        "auto_close": True,
        "disposition": "pup_pua",
        "defang": True,
    },
    "fp_ticket": {
        "path": "artefacts/fp_comms/fp_ticket.html",
        "title_prefix": "FP Closure",
        "auto_close": True,
        "disposition": "false_positive",
        "defang": False,
    },
    "fp_tuning_ticket": {
        "path": "artefacts/fp_comms/fp_tuning_ticket.html",
        "title_prefix": "FP Tuning Ticket",
        "auto_close": False,
        "disposition": None,
        "defang": False,
    },
    "executive_summary": {
        "path": "artefacts/executive_summary/executive_summary.html",
        "title_prefix": "Executive Summary",
        "auto_close": False,
        "disposition": None,
        "defang": False,
    },
    "security_arch_review": {
        "path": "artefacts/security_architecture/security_arch_review.html",
        "title_prefix": "Security Architecture Review",
        "auto_close": False,
        "disposition": None,
        "defang": True,
    },
}


# ---------------------------------------------------------------------------
# Main function
# ---------------------------------------------------------------------------

def save_report_to_case(
    case_id: str,
    report_type: str,
    report_text: str,
    disposition: str | None = None,
) -> dict:
    """Persist a report generated by the analyst's local Claude session.

    Parameters
    ----------
    case_id : str
        Target case ID.
    report_type : str
        One of: mdr_report, pup_report, fp_ticket, fp_tuning_ticket,
        executive_summary, security_arch_review.
    report_text : str
        Full report markdown as generated by the local session.
    disposition : str, optional
        Override disposition for auto-close.

    Returns
    -------
    dict
        Manifest with status, path, and metadata.
    """
    # Validate report type
    if report_type not in _REPORT_TYPES:
        return {
            "status": "error",
            "reason": f"Unknown report_type {report_type!r}. "
                      f"Valid: {', '.join(_REPORT_TYPES)}",
            "case_id": case_id,
            "ts": utcnow(),
        }

    cfg = _REPORT_TYPES[report_type]
    case_dir = CASES_DIR / case_id

    # Validate case exists
    if not (case_dir / "case_meta.json").exists():
        return {
            "status": "error",
            "reason": f"Case {case_id} not found.",
            "case_id": case_id,
            "ts": utcnow(),
        }

    # Dealias if aliasing is active
    alias_map = get_alias_map()
    if alias_map:
        report_text = alias_map.dealias_text(report_text)

    # Defang malicious/suspicious IOCs
    if cfg["defang"]:
        try:
            verdict_data = load_json(
                case_dir / "artefacts" / "enrichment" / "verdict_summary.json"
            )
            mal_iocs: set[str] = set(verdict_data.get("high_priority", []))
            mal_iocs.update(verdict_data.get("needs_review", []))
            if mal_iocs:
                report_text = defang_report(report_text, mal_iocs)
        except FileNotFoundError:
            pass
        except Exception as exc:
            log_error(case_id, "save_report.defang", str(exc),
                      severity="warning", traceback=tb.format_exc())

    # Prepend header
    ts = utcnow()
    header = (
        f"# {cfg['title_prefix']} — {case_id}\n\n"
        f"_Generated: {ts} | Source: Claude Desktop (client-side)_\n\n---\n\n"
    )
    full_text = header + report_text

    # Write HTML report
    out_path = case_dir / cfg["path"]
    out_path.parent.mkdir(parents=True, exist_ok=True)
    write_report(out_path, full_text, title=f"{cfg['title_prefix']} — {case_id}")


    # Auto-close if applicable
    if cfg["auto_close"]:
        try:
            from tools.index_case import index_case
            close_kwargs: dict = {"status": "closed"}
            disp = disposition or cfg["disposition"]
            if disp:
                close_kwargs["disposition"] = disp
            index_case(case_id, **close_kwargs)
        except Exception as exc:
            log_error(case_id, "save_report.auto_close", str(exc),
                      severity="warning", traceback=tb.format_exc())

    # Write manifest
    manifest = {
        "case_id": case_id,
        "report_type": report_type,
        "report_path": str(out_path),
        "source": "claude_desktop",
        "auto_closed": cfg["auto_close"],
        "disposition": disposition or cfg["disposition"],
        "status": "ok",
        "ts": ts,
    }
    manifest_path = out_path.parent / f"{out_path.stem}_manifest.json"
    save_json(manifest_path, manifest)

    return manifest
